[package]
name = "ezpzdb"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.31", features = ["derive"] }
directories = "6.0.0"
serde = "1.0.218"
serde_json = "1.0.140"
